highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://myjekyll.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# myjekyll.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Ayush Watnani's Resume
name: Ayush Watnani
email: ayushwatnani@email.com
email_full: mailto:ayushwatnani@email.com
website: ayushwatnani.github.io
website_full: https://ayushwatnani.github.io
github: ayushwatnani
#twitter: twitter
tel: +91 81035 97224
tel_full: tel:+918103597224

google_maps: 'https://goo.gl/maps/7c11cbzF2k32'
address:
  street: 61/3 Nehru Nagar West
  postcode: 490020
  city: Bhilai
  country: India
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
